### ISSUE TITLE
Microsoft SmartScreen prevented an unrecognized app from starting

### ISSUE THREAD

**Issue by dbethke** [yzgyyang/wsl-tray#1]
Received this message when running:

Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

App: | wsl-tray_v0.2_x64.exe
Publisher: | Unknown publisher

**Comment by yzgyyang** [comment]
I have added version and author info to the .exe for future releases (#3) so it is more recognizable with SmartScreen. However, this issue cannot be solved completely even if I sign the release with a paid certificate - it was determined by Microsoft. For more info, please take a look at https://stackoverflow.com/questions/33414291/how-can-i-stop-my-installer-from-triggering-windows-10s-this-app-has-been-bloc/33505832#33505832.

Please rest assured that this app is safe to use, and just bypass this message. Thanks.
